[env]
#### define the binary path ###
# the binary path for ppc-pro-node and ppc-gateway-service
binary_path = "/data/home/wedpr/WeDPR-Component/cpp/build/bin"
# the spdz path
spdz_home = ""
# the dist path for wedpr-site
wedpr_site_dist_path = "/data/home/wedpr/WeDPR/wedpr-site/dist/"
# the dist path for wedpr-dir
wedpr_pir_dist_path = "/data/home/wedpr/WeDPR/wedpr-pir/dist/"
# the wedpr model source path,
# pls clone from https://github.com/WeBankBlockchain/WeDPR-Component
wedpr_model_source_path = "/data/home/wedpr/WeDPR-Component/python/"

# use docker mode or not
docker_mode = true

#### define the docker images desc ###
wedpr_gateway_service_image_desc = "fiscoorg/wedpr-gateway-service:v3.0.0"
wedpr_node_service_image_desc = "fiscoorg/wedpr-pro-node-service:v3.0.0"
wedpr_mpc_service_image_desc = "fiscoorg/wedpr-mpc-service:v3.0.0"
wedpr_jupyter_worker_image_desc = "fiscoorg/wedpr-jupyter-worker:v3.0.0"
wedpr_model_image_desc = "fiscoorg/wedpr-model-service:v3.0.0"
wedpr_site_image_desc = "fiscoorg/wedpr-site:v3.0.0"
wedpr_pir_image_desc = "fiscoorg/wedpr-pir:v3.0.0"


deploy_dir = "wedpr-example"
# the wedpr zone(used to distinguish different privacy computing environments)
zone = "wedpr.zone.default"

# the blockchain config
[blockchain]
# Required, the group id
blockchain_group = "group0"
# Required, the blockchain peers
blockchain_peers = []
# Required, the blockchain cert path
blockchain_cert_path = ""
# Required, the contract address for recorder factory contract
recorder_factory_contract_address = ""
# Required, the contract address for sequencer contract
sequencer_contract_address = ""

[crypto]
# the gateway-service enable ssl or not, default enable ssl
gateway_disable_ssl = false
# the gateway-service enable sm-ssl or not, default disable sm-ssl
gateway_sm_ssl = false
# the rpc use sm-ssl or not
rpc_sm_ssl = false
# use sm-crypto or not
sm_crypto = false

[[agency]]
name = "agency0"
#the time of the gateway holding and waiting to dispatcher the unsynced task, in minutes
holding_msg_minutes = 30
wedpr_api_token = ""

    [agency.gateway]
    deploy_ip=["127.0.0.1:2"]
    # gateway listen ip
    listen_ip="0.0.0.0"
    # gateway listen start port
    listen_port=40300
    # the thread count
    thread_count = 4
    # the grpc config
    # gateway grpc server listen ip
    grpc_listen_ip="0.0.0.0"
    # gateway grpc server listen start port
    grpc_listen_port=40600
    # gateway connected peers, should be all of the gateway peers info
    [[agency.gateway.peers]]
        agency = "agency0"
        endpoints = ["127.0.0.1:40300", "127.0.0.1:40301"]
    [[agency.gateway.peers]]
        agency = "agency1"
        endpoints = ["127.0.0.1:40320", "127.0.0.1:40321"]

    # configuration for hdfs
    [agency.hdfs]
        user = "root"
        home = "/user/wedpr/agency0"
        name_node = "127.0.0.1"
        name_node_port = 9000
        webfs_port = 50070
        token = ""
        # enable auth or not, default is false
        enable_krb5_auth = false
        # the hdfs kerberos auth principal, used when enable_krb5_auth
        auth_principal = "root@NODE.DC1.CONSUL"
        # the hdfs kerberos auth password, used when enable_krb5_auth
        auth_password = ""
        # the ccache path, used when enable_krb5_auth
        ccache_path = "/tmp/krb5cc_ppc_node"
        # the krb5 conf path
        krb5_conf_path = "conf/krb5.conf"
        # keytab path
        krb5_keytab_path = ""
        # auth host name override
        auth_host_name_override = ""

    # the agency mysql configuration
    [agency.mysql]
        host = "127.0.0.1"
        port = "3306"
        user = "root"
        password = "Admin123!"
        database = "agency0"

    #configuration for wedpr site
    [agency.site]
        # the site deploy ip
        deploy_ip=["127.0.0.1:2"]
        # the server port
        server_start_port = "16000"

    # configuration for wedpr pir
    [agency.pir]
        # the pir deploy ip
        deploy_ip=["127.0.0.1:2"]
        # the server start port
        server_start_port = "17000"
    # configuration for wedpr model
    [agency.model]
        deploy_ip = ["127.0.0.1:2"]
        server_start_port = "18000"

    # configuration for wedpr jupyter worker
    [agency.jupyter_worker]
        deploy_ip = ["127.0.0.1:1"]
        # the server start port
        server_start_port = "19000"
        jupyter_external_ip = ""

    # configuration for mpc
    [agency.mpc]
        deploy_ip = ["127.0.0.1:1"]
        # the server start port
        server_start_port = "20000"
        external_ip = ""

    # configuration for the wedpr nodes
    [[agency.node]]
        # disable the ra2018 psi or not, default enable ra2018
        disable_ra2018 = true
        deploy_ip=["127.0.0.1:2"]
        # node name, Notice: node_name in the same agency and group must be unique
        node_name = "node0"
        # node grpc server listen ip
        grpc_listen_ip="0.0.0.0"
        # node grpc server listen port
        grpc_listen_port=40402
        # the components
        components = "node"
        # the rpc config for the node
        [agency.node.rpc]
            listen_ip = "0.0.0.0"
            listen_port = 10200
            thread_count = 4 
        # the ra2018 config for the node
        [agency.node.ra2018psi]
            # The database used to store cuckoo-filter
            database = "ra2018_0"
            # The capacity of the cuckoo filter in MB, the default is 1MB
            cuckoofilter_capacity = 1
            # The length of each element of the cuckoo filter (bits), default 64bits
            cuckoofilter_tagBits = 64
            # The number of buckets for the cuckoo filter, the default is 4
            cuckoofilter_buckets_num = 4
            # When the cuckoo filter replaces an element, the maximum number of element replacements allowed
            cuckoofilter_max_kick_out_count = 20
            # The trash-bucket-size for the cuckoo-filter
            trash_bucket_size = 10000
            # The cuckoo filter capacity that can be cached in memory in MB
            cuckoofilter_cache_size = 256
            # Cache size in MB
            psi_cache_size = 1024
            # When reading large files, the line size loaded into memory each time, default is 100w, -1 means load the max-size-of data
            data_batch_size = 1000000
            # use hdfs to store the cuckoo-filter or not
            use_hdfs = false
        # the storage config
        [agency.node.storage]
            host = "127.0.0.1"
            # the mysqlx_port
            port = 33060
            user = "wedpr"
            password = ""
            database = ""

[[agency]]
name = "agency1"
#the time of the gateway holding and waiting to dispatcher the unsynced task, in minutes
holding_msg_minutes = 30
wedpr_api_token = ""

    [agency.gateway]
    deploy_ip=["127.0.0.1:2"]
    # gateway listen ip
    listen_ip="0.0.0.0"
    # gateway listen start port
    listen_port=40320
    # the thread count
    thread_count = 4
    # the grpc config
    # gateway grpc server listen ip
    grpc_listen_ip="0.0.0.0"
    # gateway grpc server listen start port
    grpc_listen_port=40620
    # gateway connected peers, should be all of the gateway peers info
    [[agency.gateway.peers]]
        agency = "agency0"
        endpoints = ["127.0.0.1:40300", "127.0.0.1:40301"]
    [[agency.gateway.peers]]
        agency = "agency1"
        endpoints = ["127.0.0.1:40320", "127.0.0.1:40321"]

    # configuration for hdfs
    [agency.hdfs]
        user = "root"
        home = "/user/wedpr/agency1"
        name_node = "127.0.0.1"
        name_node_port = 9000
        webfs_port = 50070
        token = ""
        # enable auth or not, default is false
        enable_krb5_auth = false
        # the hdfs kerberos auth principal, used when enable_krb5_auth
        auth_principal = "root@NODE.DC1.CONSUL"
        # the hdfs kerberos auth password, used when enable_krb5_auth
        auth_password = ""
        # the ccache path, used when enable_krb5_auth
        ccache_path = "/tmp/krb5cc_ppc_node"
        # the krb5 conf path
        krb5_conf_path = "conf/krb5.conf"
        # auth host name override
        auth_host_name_override = ""

    # the agency mysql configuration
    [agency.mysql]
        host = "127.0.0.1"
        port = "3306"
        user = "root"
        password = "Admin123!"
        database = "agency1"

    #configuration for wedpr site
    [agency.site]
        # the site deploy ip
        deploy_ip=["127.0.0.1:2"]
        # the server port
        server_start_port = "26000"

    # configuration for wedpr pir
    [agency.pir]
        # the pir deploy ip
        deploy_ip=["127.0.0.1:2"]
        # the server start port
        server_start_port = "27000"

    # configuration for wedpr model
    [agency.model]
        deploy_ip = ["127.0.0.1:2"]
        server_start_port = "28000"

    # configuration for wedpr jupyter worker
    [agency.jupyter_worker]
        deploy_ip = ["127.0.0.1:1"]
        # the server start port
        server_start_port = "29000"
        jupyter_external_ip = ""

    # configuration for mpc
    [agency.mpc]
        deploy_ip = ["127.0.0.1:1"]
        # the server start port
        server_start_port = "30000"
        external_ip = ""

    # configuration for the wedpr nodes
    [[agency.node]]
        # disable the ra2018 psi or not, default enable ra2018
        disable_ra2018 = true
        deploy_ip=["127.0.0.1:2"]
        # node name, Notice: node_name in the same agency and group must be unique
        node_name = "node0"
        # node grpc server listen ip
        grpc_listen_ip="0.0.0.0"
        # node grpc server listen port
        grpc_listen_port=40422
        # the componet
        components = "node"
        # the rpc config for the node
        [agency.node.rpc]
            listen_ip = "0.0.0.0"
            listen_port = 10220
            thread_count = 4 
        # the ra2018 config for the node
        [agency.node.ra2018psi]
            # The database used to store cuckoo-filter
            database = "ra2018_1"
            # The capacity of the cuckoo filter in MB, the default is 1MB
            cuckoofilter_capacity = 1
            # The length of each element of the cuckoo filter (bits), default 64bits
            cuckoofilter_tagBits = 64
            # The number of buckets for the cuckoo filter, the default is 4
            cuckoofilter_buckets_num = 4
            # When the cuckoo filter replaces an element, the maximum number of element replacements allowed
            cuckoofilter_max_kick_out_count = 20
            # The trash-bucket-size for the cuckoo-filter
            trash_bucket_size = 10000
            # The cuckoo filter capacity that can be cached in memory in MB
            cuckoofilter_cache_size = 256
            # Cache size in MB
            psi_cache_size = 1024
            # When reading large files, the line size loaded into memory each time, default is 100w, -1 means load the max-size-of data
            data_batch_size = 1000000
            # use hdfs to store the cuckoo-filter or not
            use_hdfs = false
        # the storage config
        [agency.node.storage]
            host = "127.0.0.1"
            # the mysqlx_port
            port = 33060
            user = "wedpr"
            password = ""
            database = ""
